mappings:
  CwpInitialisationFilter: CWP\Core\Config\CwpInitialisationFilter
  CustomHtmlEditorFieldToolbar: CWP\Core\Extension\CustomHtmlEditorFieldToolbar
  CwpControllerExtension: CWP\Core\Extension\CwpControllerExtension
  CwpHtmlEditorConfig: CWP\Core\Extension\CwpHtmlEditorConfig
  LoginAttemptNotifications_LeftAndMain: CWP\Core\Extension\LoginAttemptNotifications
  RichLinksExtension: CWP\Core\Extension\RichLinksExtension
  CwpAtomFeed: CWP\Core\Feed\CwpAtomFeed
  CwpSearchIndex: CWP\Core\Model\CwpSearchIndex
  SolrSearchIndex: CWP\Core\Model\CwpSolrIndex
  CwpStatsReport: CWP\Core\Report\CwpStatsReport
  CwpSolr: CWP\Core\Search\CwpSolr
  RichLinksExtensionTest: CWP\Core\Tests\RichLinksExtensionTest
  CwpControllerExtensionTest: CWP\Core\Tests\CwpControllerExtensionTest
  CwpStatsReportTest: CWP\Core\Tests\CwpStatsReportTest
  AtomFeedTest: CWP\Core\Tests\AtomFeedTest
  AtomFeedTest_ItemA: CWP\Core\Tests\AtomFeedTest_ItemA
  AtomFeedTest_ItemB: CWP\Core\Tests\AtomFeedTest_ItemB
  AtomFeedTest_ItemC: CWP\Core\Tests\AtomFeedTest_ItemC
  AtomTags_Test: CWP\Core\Tests\AtomTags_Test
